default:
  host: mysql
  port: 3306
  adapter: mysql2
  encoding: utf8
  socket: /tmp/mysql.sock
  database: <%= ENV.fetch("MYSQL_DATABASE") %>
  username: <%= ENV.fetch("MYSQL_USER") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") %>


